site_name: EAM Documentation
theme:  
  name: material
  theme:
  language: en
  features:
    - navigation.footer
extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/huddeldaddel/eamdocs
extra_javascript:
  - static/js/tablesort.min.js
  - static/js/tablesort.js
plugins:  
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/
      num_workers: 8
  - search
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - tables